name: Upload PyPI Release

on:
  release:
    types:
      - published
  # pull_request:
  # push:

jobs:
  build_wheel_on_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine cython auditwheel patchelf>=0.14
      - name: Build wheel
        run: |
          python setup.py sdist 

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  build_wheel_on_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine cython
      - name: Build wheel
        run: |
          python setup.py sdist

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheel_on_linux, build_wheel_on_windows]
    permissions:
      id-token: write 
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
